### one
POST 127.0.0.1:65301/resource/one
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzbm93IiwiaWF0IjoxNjg4NTcwNDI1LCJleHAiOjE2ODg1Nzc2MjV9.iq14KejCuQjiwaQmkwRma4Cwe6j8KuSahZeE_X9p2tw
Content-Type: application/json

{
}

### two
POST 127.0.0.1:65301/resource/two
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzbm93IiwiaWF0IjoxNjg4NTcwNDI1LCJleHAiOjE2ODg1Nzc2MjV9.iq14KejCuQjiwaQmkwRma4Cwe6j8KuSahZeE_X9p2tw
Content-Type: application/json

{
}
