### one
POST 127.0.0.1:65301/resource/one
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc1JlZnJlc2hUb2tlbiI6ZmFsc2UsInN1YiI6InNub3ciLCJpYXQiOjE2ODgzOTQxODEsImV4cCI6MTY4ODQwMTM4MX0.tFP-SEIg9VlFaaVqzTLuUoqMMN1lDd3tflKAs2QtjqI
Content-Type: application/json

{
}

### two
POST 127.0.0.1:65301/resource/two
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc1JlZnJlc2hUb2tlbiI6ZmFsc2UsInN1YiI6InNub3ciLCJpYXQiOjE2ODgzOTQxODEsImV4cCI6MTY4ODQwMTM4MX0.tFP-SEIg9VlFaaVqzTLuUoqMMN1lDd3tflKAs2QtjqI
Content-Type: application/json

{
}
