### one
POST 127.0.0.1:65301/resource/one
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJyZWZyZXNoVG9rZW4iOmZhbHNlLCJzdWIiOiJzbm93IiwiaWF0IjoxNjg4NjkyOTM3LCJleHAiOjE2ODg3MDAxMzd9.3xFVCHdOjo1gve_tfhJGasKK2RXNcPyTKOTveSwd9J4
Content-Type: application/json

{
}

### two
POST 127.0.0.1:65301/resource/two
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJyZWZyZXNoVG9rZW4iOmZhbHNlLCJzdWIiOiJzbm93IiwiaWF0IjoxNjg4NjkyOTM3LCJleHAiOjE2ODg3MDAxMzd9.3xFVCHdOjo1gve_tfhJGasKK2RXNcPyTKOTveSwd9J4
Content-Type: application/json

{
}
