xxl-job:
  address: "http://${xxl.job.admin.addr}"
  executor:
    appname: service-template
    port: ${random.int[60505,60566]}
    log-path: ~/logs/project-actual/xxl-job/
    log-retention-days: 30
