server:
  port: 65301

spring:
  application:
    name: service_template
  main:
    allow-circular-references: true
  aop:
    auto: false
    proxy-target-class: false
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application-datasource-druid.yml
      - classpath:application-mybatis.yml
      - classpath:application-dubbo.yml
      - classpath:application-log.yml
      - classpath:application-management.yml
      - classpath:application-xxljob.yml
      # - classpath:application-mq-kafka.yml
      # - classpath:application-mq-rocketmq.yml