logging:
  level:
    root: info
    com.code: debug
    # org.apache.dubbo: debug
    # org.springframework.web: debug
    # org.springframework.beans.factory: trace
    org.springframework.web.servlet.mvc.method.annotation: debug