spring:
  authorization:
    custom:
      server:
        issuer: http://notuptoyou.com:65000
        default-registration-client:
          client-id: demo-client
          client-secret: 123456
          client-name: Demo客户端
          scopes: openid,read,write