### 新增用户
POST http://127.0.0.1:65001/test/save
Content-Type: application/json; charset=UTF-8

{
  "name": "测试",
  "age": 16
}

### 分页查询
POST http://127.0.0.1:65001/test/page
Content-Type: application/json; charset=UTF-8

{
  "currentPage": 2,
  "pageSize": 3
}
