### one 必须用 accessToken 访问（ 因为配置了 hasAnyAuthority ）
GET http://notuptoyou.com:65002/one/aaa
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODkyMzI5MzUsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiLCJ3cml0ZSJdLCJpc3MiOiJodHRwOi8vbm90dXB0b3lvdS5jb206NjUwMDEiLCJleHAiOjE2ODkyNDAxMzUsImlhdCI6MTY4OTIzMjkzNX0.BGthADrxXU1aZtLTxQXdpeycYPT26StwGk8ylWmJ7mm1tq4vONvCdTwr954diWgho0u5nEy77Ft4ioB3cX3QpbJHIsHM4vN70r_PKz3-Q531wCZJaDLlX5jnw6xN6-9poWxHmEFSjPbqAS2o9Q5KOolyaidUV2IkrL9UBGC1cdoQuoh48YTLa_UUfLRNrY0J9alTaFe5p4y7-WssckQkrI3h3dssFejazi2T_q8MkYPPuu0Cc5N8gwzSnOQmNNC7C-6IrKqW1iU68GlX3oBpDYqkdtvteRoSkxcrG3lxkosIR6tZJhY7P0IuBo2D5b1dCm3eeFV1Z94atUiy4ABcRA

### two 必须用 accessToken 访问（ 因为配置了 hasAnyAuthority ）
GET http://notuptoyou.com:65002/one/bbb
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODg4NzQyNzgsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiLCJ3cml0ZSJdLCJpc3MiOiJodHRwOi8vbm90dXB0b3lvdS5jb206NjUwMDAiLCJleHAiOjE2ODg4ODE0NzgsImlhdCI6MTY4ODg3NDI3OH0.cRFP6ll2yMGjJIR04JdrrNlwVlfRtWnrzjwwHmcxOc2s8-THIXatSfKylO_HCSUDNj_DSkUDJvrGt9E5YsfhF5KOpTUtYa8vek-lAfXoc8iwGbDPVkUqYAhj9apeq-9FLSuvRrCvOWkrYBBEEXUwu50DMFxQddEhbqua4MKQnITlKNgkffB0N0aHO5jd3jYLD08mTGgOajWocZw-w2jFFOIxPO2nBKQi1LYaGiAoK1Ee637Qpsg7z_bxGZAfWIPvya2jyAbRCVrhyUDpchX6QiQBI1n8rZbOsHPqKz58dVC6EuVEVjmRSo8UeAEv6mD-jLvS_4gQzxC_ADDGzurETw

### currentUser 可以用 idToken/accessToken 访问，获取到的是 accessToken 或 idToken（ 入参是 什么 出参就是 什么 ）
GET http://notuptoyou.com:65002/one/currentUser
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODg4NzQyNzgsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiLCJ3cml0ZSJdLCJpc3MiOiJodHRwOi8vbm90dXB0b3lvdS5jb206NjUwMDAiLCJleHAiOjE2ODg4ODE0NzgsImlhdCI6MTY4ODg3NDI3OH0.cRFP6ll2yMGjJIR04JdrrNlwVlfRtWnrzjwwHmcxOc2s8-THIXatSfKylO_HCSUDNj_DSkUDJvrGt9E5YsfhF5KOpTUtYa8vek-lAfXoc8iwGbDPVkUqYAhj9apeq-9FLSuvRrCvOWkrYBBEEXUwu50DMFxQddEhbqua4MKQnITlKNgkffB0N0aHO5jd3jYLD08mTGgOajWocZw-w2jFFOIxPO2nBKQi1LYaGiAoK1Ee637Qpsg7z_bxGZAfWIPvya2jyAbRCVrhyUDpchX6QiQBI1n8rZbOsHPqKz58dVC6EuVEVjmRSo8UeAEv6mD-jLvS_4gQzxC_ADDGzurETw

### currentSession 可以用 idToken/accessToken 访问，返回值：false
GET http://notuptoyou.com:65002/one/currentSession
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODg4NzQyNzgsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiLCJ3cml0ZSJdLCJpc3MiOiJodHRwOi8vbm90dXB0b3lvdS5jb206NjUwMDAiLCJleHAiOjE2ODg4ODE0NzgsImlhdCI6MTY4ODg3NDI3OH0.cRFP6ll2yMGjJIR04JdrrNlwVlfRtWnrzjwwHmcxOc2s8-THIXatSfKylO_HCSUDNj_DSkUDJvrGt9E5YsfhF5KOpTUtYa8vek-lAfXoc8iwGbDPVkUqYAhj9apeq-9FLSuvRrCvOWkrYBBEEXUwu50DMFxQddEhbqua4MKQnITlKNgkffB0N0aHO5jd3jYLD08mTGgOajWocZw-w2jFFOIxPO2nBKQi1LYaGiAoK1Ee637Qpsg7z_bxGZAfWIPvya2jyAbRCVrhyUDpchX6QiQBI1n8rZbOsHPqKz58dVC6EuVEVjmRSo8UeAEv6mD-jLvS_4gQzxC_ADDGzurETw



### 总结：Server、Client 用 Session 访问，Resource 用 idToken/accessToken 访问（）