server:
  port: 65001

spring:
  application:
    name: SERVICE_TEST
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application-datasource-druid.yml
      - classpath:application-mybatis.yml
      - classpath:application-dubbo.yml
      - classpath:application-log.yml
  main:
    allow-circular-references: true
