### one
GET http://notuptoyou.com:65101/one/aaa
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJhenAiOiJkZW1vLWNsaWVudCIsImF1dGhfdGltZSI6MTY4NjA2Mzk2OSwic2NvcGUiOlsicmVhZCIsIm9wZW5pZCJdLCJpc3MiOiJodHRwOi8vbm90dXB0b3lvdS5jb206NjUwMDAiLCJleHAiOjE2ODYwNjU3NzQsImlhdCI6MTY4NjA2Mzk3NCwibm9uY2UiOiJfYnpGWlZ2eVJjZlp2Q3p1aFN5a0JwR0d0ZXhuMHZXeG05UlU2ZkxRNE9JIiwic2lkIjoiYkh3VGd3dk92OGNOWm80QVdPQWZRZlUxSDRwbmoydXVjY2l2VnBkeHA2TSJ9.IaNs_FVn5Sy9t8qBZAAwRrDobtw3PY8ZKJ5mqWikgDUwkF_ayLs6K52X3sxOLIIC237P9SqdW13DytiAhixS_UGBkUIad-tv_S6RAHuVh_DieijlhwKQf8O-muXIqZXhcqfmpyuz5TKREbRYi1jhplSBh55Otnc_TziukAllCUqYlfkmKaDBCNvF4VF_qjlkL2Zy_QsOKSaUmpoKYh0_VBMZ_mS7iyvdPgC_mJkEKsi03307Y6UXAX0_sZ_ZybCZyJQ2ZNAvMefeZgP6XQv_GgUxoOsPxV4XldfGf8YFmG-30fYmasprhITNd7GuNVPCA4wjQofTaOdlBWOFA1tTmQ

### two
GET http://notuptoyou.com:65101/one/bbb
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJhenAiOiJkZW1vLWNsaWVudCIsImF1dGhfdGltZSI6MTY4NjA2Mzk2OSwic2NvcGUiOlsicmVhZCIsIm9wZW5pZCJdLCJpc3MiOiJodHRwOi8vbm90dXB0b3lvdS5jb206NjUwMDAiLCJleHAiOjE2ODYwNjU3NzQsImlhdCI6MTY4NjA2Mzk3NCwibm9uY2UiOiJfYnpGWlZ2eVJjZlp2Q3p1aFN5a0JwR0d0ZXhuMHZXeG05UlU2ZkxRNE9JIiwic2lkIjoiYkh3VGd3dk92OGNOWm80QVdPQWZRZlUxSDRwbmoydXVjY2l2VnBkeHA2TSJ9.IaNs_FVn5Sy9t8qBZAAwRrDobtw3PY8ZKJ5mqWikgDUwkF_ayLs6K52X3sxOLIIC237P9SqdW13DytiAhixS_UGBkUIad-tv_S6RAHuVh_DieijlhwKQf8O-muXIqZXhcqfmpyuz5TKREbRYi1jhplSBh55Otnc_TziukAllCUqYlfkmKaDBCNvF4VF_qjlkL2Zy_QsOKSaUmpoKYh0_VBMZ_mS7iyvdPgC_mJkEKsi03307Y6UXAX0_sZ_ZybCZyJQ2ZNAvMefeZgP6XQv_GgUxoOsPxV4XldfGf8YFmG-30fYmasprhITNd7GuNVPCA4wjQofTaOdlBWOFA1tTmQ