### one
GET http://notuptoyou.com:65101/one/aaa
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJhenAiOiJkZW1vLWNsaWVudCIsImF1dGhfdGltZSI6MTY4NTg2OTU1MCwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg1ODcxMzUwLCJpYXQiOjE2ODU4Njk1NTAsIm5vbmNlIjoidFZJTWtNLUlVaDdZZTQyR00zM2Z2R0d1THlDUjQ4ZGRrenZtQ3YwNzg4USIsInNpZCI6InFyc0EtUE5jQ2VDZGtqQkFCNDdtX0ctZWNzYXoyTXBGY2VXMndwZDZuZXMifQ.PFfL-PvCx8CmPGIkgnlLz0RLv07oqJJK-0mLVXNu2_SRTWqvZ7IH89bgoO-qLpQz7BcTJwl4H1eEvnNOrEv-TeugfAuqcDIKWPZFtBAdWsWAmfKuPJuf3HJHxNeo3eO-LlSGv9Nf_drjF4C6hwWZAvIZ034M8DJS2Z7Mt07cvthDjdbWOrmp7NR38ZK8qQ6ID8b8BhQz2rMMVZLcN4XglEG3lbQMsg4ZSMWMPieanQswN-Rvs9khEAbMzn5kNMvSyCNtm57So5S1-fMAf4XZnfUFaCl_CbDeQ8G6KFL1HJToaNcPTx1_-rvrcFtPzgdMPyGtEnS4esQFSOcieTGd1Q

### two
GET http://notuptoyou.com:65101/one/bbb
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxMjM0NTYiLCJhdWQiOiJ1c2VyX2NlbnRlciIsIm5iZiI6MTY4NTYxMzkwMywic2NvcGUiOlsicmVhZCJdLCJpc3MiOiJodHRwOi8vbm90dXB0b3lvdS5jb206NjUwMDAiLCJleHAiOjE2ODU2MjExMDMsImlhdCI6MTY4NTYxMzkwM30.Mly1bPU_e4CGBCVPoE8SjeVBVOQkhKu9QhdpGg5y-tE_LCjKuBlxeUkUxZ_1zr08RXO-IHfbz_RmHICH_b73glRMs2KjQ_1T7CvjbACjMUk302jzGWyLfcynOILbrw2sz7YYT0xsGSA5v2T-mpmAF_mAmdx9YpsV3vZbqIIXg0urrNVYD-Dl-DXxSxqMqe-Ol-kgMbYa9BKSTBGgMntvoeWQYYAKfy6CDXH38X3nYgnE_v-hBs5fgH6OiHwmI7_faUdfudq0yY5v-jwbntn_o8gX9rGatpf8I6N9Ykr3yIcli3U7rZZvacBNQjI6BKK--LZuPQ5_KluCJsPTor0YAQ