server:
  port: 65001
spring:
  application:
    name: xxl-job-springboot
xxl:
  job:
    admin:
      addresses: http://${xxl.job.admin.addr}/
    executor:
      appname: ${spring.application.name}
      ip: 124.223.36.171
      port: 65031
      logpath: ~/logs/xxl-job/
      logretentiondays: 30
