spring:
  security:
    oauth2:
      client:

        registration:
          # 客户端：与注册时保持一致
          UserCenter:
            client-id: user_center
            client-secret: user_center_123456
            client-name: ${spring.application.name}
            scope: read,write
            authorization-grant-type: authorization_code
            provider: infraAuthorization
            redirect-uri: '{baseUrl}/{action}/oauth2/code/user_center'
            # 认证方法
            client-authentication-method: client_secret_basic

        provider:
          # 服务提供地址
          infraAuthorization:
            # 请求授权码地址
            authorization-uri: http://notuptoyou.com:65000/oauth2/authorize
            # 请求令牌地址
            token-uri: http://notuptoyou.com:65000/oauth2/token
            # 获取用户信息的地址：必须和 infra-authorization 服务中自己定义的 Controller 的 RequestMapping 路径一致
            user-info-uri: http://notuptoyou.com:65000/oauth2/user
            # 获取到的用户信息中用户名的属性名
            user-name-attribute: name
            user-info-authentication-method: GET