### test 正常访问
GET http://notuptoyou.com:65001/test
Content-Type: application/json
Cookie: JSESSIONID=17816B1086777DDA22B229FD0304BBA4

### currentUser 没 idToken 、accessToken ，获取到的信息里包含 sessionId
GET http://notuptoyou.com:65001/currentUser
Content-Type: application/json
Cookie: JSESSIONID=17816B1086777DDA22B229FD0304BBA4

### currentSession 有（ 域：notuptoyou.com ）
GET http://notuptoyou.com:65001/currentSession
Content-Type: application/json
Cookie: JSESSIONID=17816B1086777DDA22B229FD0304BBA4


### 总结：Server、Client 用 Session 访问，Resource 用 accessToken 访问