### 获取 token
POST http://notuptoyou.com:65000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZGVtby1jbGllbnQ6c2VjcmV0 # 取值：代码里配置的 clientId:clientSecret 进行 Base64 编码（如当前的：demo-client:secret => ZGVtby1jbGllbnQ6c2VjcmV0）

# grant_type：授权类型，redirect_uri：代码里配置的 redirectUri ，code：认证后返回的 code
grant_type = authorization_code &
redirect_uri = https://www.bing.com &
code = pBBXzgUPsIpFkyFDcn7F7-HA9-M8AJ1_CCAOA29fDjDZNBKsa7EEK79xSC4FaPJrgLOrsMmHnN8wA0WVQl8vwk_QNwjaDfDTpqYywRd3CWCNE_EHGMk2V6fDMgbJ2Uz1


### 刷新 token
POST http://notuptoyou.com:65000/oauth2/token
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic ZGVtby1jbGllbnQ6c2VjcmV0

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"
Content-Type: text/plain

refresh_token

--WebAppBoundary
Content-Disposition: form-data; name="refresh_token"
Content-Type: text/plain

# 获取 token 调用返回的 refresh_token
IOk2Ja1hEBQo6DZVeEC8Xz9twavpOmufFGZ4ivHP3Z5dYIVeq44BaqfEJWgkniourk0mfxjQS8fzcoLUht1HM9ASJF3dvjRXJiL1TabpLaGH-2GCx-QYOFHG49DKYPZD
