logging:
  level:
    root: debug
    org: info
    com: info
    sun: info
    javax: info
    io: info
    com.code: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.jdbc: debug
    org.springframework.transaction: debug
