jdbc:
  url: jdbc:h2:mem:basis_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
  username: ${mysql.username}
  password: ${mysql.password}
  driver: org.h2.Driver

spring:
  h2:
    console:
      settings:
        trace: true
        web-allow-others: true
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
      username: ${mysql.username}
      password: ${mysql.password}
      continue-on-error: false
      schema-locations:
        - classpath*:db/schema/schema.sql
#      data-locations:
#        - classpath:db/data/data.sql