### test
POST http://127.0.0.1:65001/gateway
Content-Type: application/json; charset=UTF-8

{
  "api": "template.test"
}

### 保存
POST http://127.0.0.1:65001/gateway
Content-Type: application/json; charset=UTF-8

{
  "api": "template.save",
  "content": "{\"price\":6.67,\"coverImgUrl\":\"https://google.com\"}"
}
