server:
  port: 65000
spring:
  application:
    name: infra_authorization
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application-mybatis-plus.yml
      - classpath:application-keystore.yml
      - classpath:application-log.yml