spring:
  datasource:
    # url: jdbc:h2:mem:spring_authorization_actual;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    url: jdbc:h2:mem:oauth2-server-resource-client;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
