spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
  sql:
    init:
      mode: embedded
      continue-on-error: false
      schema-locations: classpath*:sql/ddl.sql
      data-locations: classpath*:sql/dml.sql