server:
  port: 65101
spring:
  application:
    name: oauth_mode_code_resource
  config:
    import:
      - classpath:application-s-jwt.yml
      - classpath:application-s-oauth.yml
      - classpath:application-log.yml