server:
  port: 60000
spring:
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application-mybatis-plus.yml
      - classpath:application-security.yml
      - classpath:application-log.yml