### 获取用户信息
GET http://notuptoyou.com:65000/oauth2/user
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtb19jbGllbnQiLCJuYmYiOjE2ODU3MDE2MTMsInNjb3BlIjpbInJlYWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg1NzA4ODEzLCJpYXQiOjE2ODU3MDE2MTN9.aWiHbFEWDmXKqZC60D6LRkG7-8YtthUGGtBvTVMkCTpJNSLe8xaDkg76n-EXizUtR0oQZtEGdmwSzxabxEyEKlSpSJy8hzqsrN9r1zbk85H_EZkUxFHKNuFxSYKj1jx_j87H-mE6OVyyS6XI3Fpn0Xnav6orn2RvxEr_5KKSWu45XJhd8fkGfcWSJTCCagJ5XXcMVGZkeyhoTUVHBfAUyHrZMXTD9PwfCp_mnnnUmQ9rsmLsYJIyTiOCIiGuVUjrC5kWH9utyC_UAqEjlRYqaF27nGFmeQjEcrJnLFJ5PygDucVVCRP2y_JrjoNOLb1xo7ldf5zoY9IyPuokmhlJtA
