jdbc:
  first:
    url: ${mysql.url}/sharding_db0?${mysql.url.params}
    username: ${mysql.username}
    password: ${mysql.password}
    driver: com.mysql.cj.jdbc.Driver
  second:
    url: ${mysql.url}/sharding_db1?${mysql.url.params}
    username: ${mysql.username}
    password: ${mysql.password}
    driver: com.mysql.cj.jdbc.Driver