spring:
  datasource:
    url: ${mysql.url}/frame_relational?${mysql.url.params}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
