### 获取 token
POST http://notuptoyou.com:65000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zmlyc3RfY2xpZW50OjEyMzQ1Ng== # 取值：代码里配置的 clientId:clientSecret 进行 Base64 编码（如当前的：first_client:123456 => Zmlyc3QtY2xpZW50OjEyMzQ1Ng==）

# grant_type：授权类型，redirect_uri：代码里配置的 redirectUri ，code：认证后返回的 code
grant_type = authorization_code &
redirect_uri = https://www.bing.com &
code = f1fFn6a4VVHjbP_3h5yCA2kmrBm_rawoF6Uud7rxWjZUCGBfINOvr_t1PbUSrLucs0BfzVgTOwcmLR1LNGeKRwBoZbkVyiHu6wHqFhNv0eDjQecRpazajc7B-wtzx90H


### 刷新 token
POST http://notuptoyou.com:65000/oauth2/token
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic Zmlyc3RfY2xpZW50OjEyMzQ1Ng==

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"
Content-Type: text/plain

refresh_token

--WebAppBoundary
Content-Disposition: form-data; name="refresh_token"
Content-Type: text/plain

# 获取 token 调用返回的 refresh_token
xE8BkjDgja4Ta0tdGQ1nEZEWuFUx8ykf0hNcjdCUK4u-yhbsRlZ2PnbvHJJxs3P5QQjvYi-KkysUXwuvu6DFL91uNeuNBvewUZ7k9mAYA9qfpg3dqx8qgUfYaQj1V6DG
