spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:basis_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    username: snow
    password: snow
  h2:
    console:
      settings:
        trace: true
        web-allow-others: true
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2
      mode: always
      schema-locations:
        - classpath*:db/schema/schema.sql
#      data-locations: 
#        - classpath:db/data/data.sql
