jdbc:
  simple:
    jdbc-url: ${mysql.url}/frame_relational?${mysql.url.params}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sharding:
    jdbc-url: jdbc:shardingsphere:classpath:application-sharding.yml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver