spring:
  security:
    oauth2:
      client:
        registration:
          # 注意要与 Server 的设置保持一致
          first-registration:
            client-id: demo-client
            client-secret: 123456
            client-name: Demo客户端
            scope: openid,read,write
            redirect-uri: http://127.0.0.1:65001/login/oauth2/code/{registrationId}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            provider: demo-provider
        provider:
          # 服务提供地址
          demo-provider:
            issuer-uri: http://notuptoyou.com:65000