spring:
  security:
    oauth2:
      client:
        registration:
          # 客户端：与 Server 的设置保持一致
          demoClient:
            client-id: demo_client
            client-secret: 123456
            client-name: demo_client_name
            scope: read,write
            authorization-grant-type: authorization_code
            provider: demoAuthorization
            redirect-uri: http://127.0.0.1:65001/redirect
            # 认证方法
            client-authentication-method: client_secret_basic

        provider:
          # 服务提供地址
          demoAuthorization:
            issuer-uri: http://notuptoyou.com:65000