### one 必须用 accessToken 访问（ 因为配置了 hasAnyAuthority ）
GET http://notuptoyou.com:65101/one/aaa
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODY4NDA4MDMsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQ4MDAzLCJpYXQiOjE2ODY4NDA4MDN9.g4UaeihQnw2hjswtwzF1xHBVJVGNUQEFeEmfG0mCmb0qVRL7mJb2GT9Q5qwY6XHCWKd3bF8854W9vll73t4MAzA7HWg3687m3c7Vut-wraYUs_-gdG5L1Uqymz3ns__-BaAHeJ8OQjOV11gIz_2VEC5TStMCQRxljpYEe-07cKCt3R-U5weaIhSjU5DZAFVDuYAhw1OXM38LqQDo8wUTqOvTo3HEkohZZeZ1fk3nqrPbUcLIHwsFwDo7o6yUhxNUFum_zfW-bQA0SMnLg4oMOzyihEzbrCldoxFLEPTiMbttkEfyotUn2zrDi_lDNhk29Uq91NkAg0SW1C9uYpWh6g

### two 必须用 accessToken 访问（ 因为配置了 hasAnyAuthority ）
GET http://notuptoyou.com:65101/one/bbb
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODY4MzkyMjIsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQ2NDIyLCJpYXQiOjE2ODY4MzkyMjJ9.H-S5mB3nRisAUv13S879oqTA9_7WCvmRqNArVZbozRXXZdlVb8iebAJQgbntgSYz_e34sXO9iq86NzhbRpmOIHmJ-0QhgD61tqZJnuf_s5x2ah6YaIOBJga91Zza4Dt88v5dtRoJpF4fdFTOIC3XTa7-jv5E5hXMMrLXR7eXNBUzp9U7D_7dGPe97hCZuNL7K0KVdSHts9XedtJAfUb_EmAZeIwMK7aFE7luO7o0_llLCT41zK6sfrEJTXoJnEMvOgq2JGD-XZlalp_m-m3ADoLtSxk6hldp5canoiu2xBybSVwOKDukxzt7F1GaRR5jRi5d2a5h5RqWyE-wqSUDSg

### currentUser 可以用 idToken/accessToken 访问，获取到的是 accessToken 或 idToken（ 入参是 什么 出参就是 什么 ）
GET http://notuptoyou.com:65101/one/currentUser
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJhenAiOiJkZW1vLWNsaWVudCIsImF1dGhfdGltZSI6MTY4Njg0MDgwMywiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQyNjAzLCJpYXQiOjE2ODY4NDA4MDMsIm5vbmNlIjoiVGlyQnlYaU1xVVl3anRQZjRIbjgzYkQtLXhTbDFqamJDVG1WZHRxSDBUMCIsInNpZCI6ImhvUXpvSVJBT0lnNVYtZV9ZVGdGSDRFOVc1UTNzS1NjM181MzhhYzFtRU0ifQ.iW1IcFSIxFkSZsyGDDPQRNWS0NMgWUavLj8p18ff0XNR87nv1h_K2SqnleTozNb3q41jYr_pHWciXZ0UONY6ggdJhDaKYMVactupzJjwX3nsD57xaxzbnG2B40VzqdukBk8ZNVzB6Oob6_Gk6A8ewfL0jH3KqK4hyIIDbIs8CJQdIL8wDacp_QTwxPFSI5SJLUiUHhEVumN6ggCuxfHGweQ0zhGL4xhfmmMZDNV3Uae7h1EEKvppOkpz6sOkWJY9UIx3JnIYMxfiEFsu6f3ud3jAO1AAuzSsEyU5biff-SrEpesyyPtKTkDqOBSxlh7Cp-KQrbNBDpf0q2TEFUqWcg

### currentSession 可以用 idToken/accessToken 访问，返回值：false
GET http://notuptoyou.com:65101/one/currentSession
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJhenAiOiJkZW1vLWNsaWVudCIsImF1dGhfdGltZSI6MTY4Njg0MDgwMywiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQyNjAzLCJpYXQiOjE2ODY4NDA4MDMsIm5vbmNlIjoiVGlyQnlYaU1xVVl3anRQZjRIbjgzYkQtLXhTbDFqamJDVG1WZHRxSDBUMCIsInNpZCI6ImhvUXpvSVJBT0lnNVYtZV9ZVGdGSDRFOVc1UTNzS1NjM181MzhhYzFtRU0ifQ.iW1IcFSIxFkSZsyGDDPQRNWS0NMgWUavLj8p18ff0XNR87nv1h_K2SqnleTozNb3q41jYr_pHWciXZ0UONY6ggdJhDaKYMVactupzJjwX3nsD57xaxzbnG2B40VzqdukBk8ZNVzB6Oob6_Gk6A8ewfL0jH3KqK4hyIIDbIs8CJQdIL8wDacp_QTwxPFSI5SJLUiUHhEVumN6ggCuxfHGweQ0zhGL4xhfmmMZDNV3Uae7h1EEKvppOkpz6sOkWJY9UIx3JnIYMxfiEFsu6f3ud3jAO1AAuzSsEyU5biff-SrEpesyyPtKTkDqOBSxlh7Cp-KQrbNBDpf0q2TEFUqWcg



### 总结：Server、Client 用 Session 访问，Resource 用 idToken/accessToken 访问（）