spring:
  datasource:
    url: jdbc:h2:mem:basis_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
