spring:
  datasource:
    url: jdbc:h2:mem:frame_relational;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
