jdbc:
  first:
    jdbc-url: ${mysql.url}/sharding_db0?${mysql.url.params}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  second:
    jdbc-url: ${mysql.url}/sharding_db1?${mysql.url.params}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver