spring:
  authorization:
    custom:
      server:
        issuer: http://notuptoyou.com:65000
        default-register-client:
          client-id: demo-client
          client-secret: 123456
          client-name: demo-client-name
          scopes: openid,read,write
          redirect-uris: http://127.0.0.1:65001/login/oauth2/code/demo-client-aaa,http://127.0.0.1:65001/authorized