### one
POST 127.0.0.1:60000/resource/one
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc1JlZnJlc2hUb2tlbiI6ZmFsc2UsInN1YiI6InNub3ciLCJpYXQiOjE2ODgyNjkyNDEsImV4cCI6MTY4ODI3NjQ0MX0.bBKu26p9UrgrgSRPyyU01qQWEhNpl7wHupnrqWjtFkU
Content-Type: application/json

{
}

### two
POST 127.0.0.1:60000/resource/two
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc1JlZnJlc2hUb2tlbiI6ZmFsc2UsInN1YiI6InNub3ciLCJpYXQiOjE2ODgyNjkyNDEsImV4cCI6MTY4ODI3NjQ0MX0.bBKu26p9UrgrgSRPyyU01qQWEhNpl7wHupnrqWjtFkU
Content-Type: application/json

{
}
