server:
  port: 65101
spring:
  application:
    name: service_one
  config:
    import:
      - classpath:application-jwt.yml
      - classpath:application-oauth.yml
      - classpath:application-log.yml