### one 必须用 accessToken 访问（ 因为配置了 hasAnyAuthority ）
GET http://notuptoyou.com:65101/one/aaa
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODc4NzI5MDQsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg3ODgwMTA0LCJpYXQiOjE2ODc4NzI5MDR9.CIzbxqbTFnOmIt7pkrvgcuR5DwqzahD996rbmWlXzyRwM0HtjUVuAhaibV2twxhcg2015kPPquoe1i0xWMEdrPV4M-94C8njt2kve3nGA_dewv4e5-_T_-litW6MlqQUxk0k6GnanBFdVogbVOR86DbQD95JF-fOSP0vD4uEMusoGNORt5K9KdHk18nkmyZkfdR_rp2bGnrviZiHx9QWUsW8sv7FOQqjb23mtxZ2eaL-beTK692k3zwx2qwnPnwe_WnQw-hufx6qgLCDZq1v9Tkc0mf9dxeh2SWffAhd7dIf2BPRnjrvhLRFXKNRZ9jv7oJ6BMbPWYBL0nixfVjM1Q

### two 必须用 accessToken 访问（ 因为配置了 hasAnyAuthority ）
GET http://notuptoyou.com:65101/one/bbb
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODc4NzI5MDQsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg3ODgwMTA0LCJpYXQiOjE2ODc4NzI5MDR9.CIzbxqbTFnOmIt7pkrvgcuR5DwqzahD996rbmWlXzyRwM0HtjUVuAhaibV2twxhcg2015kPPquoe1i0xWMEdrPV4M-94C8njt2kve3nGA_dewv4e5-_T_-litW6MlqQUxk0k6GnanBFdVogbVOR86DbQD95JF-fOSP0vD4uEMusoGNORt5K9KdHk18nkmyZkfdR_rp2bGnrviZiHx9QWUsW8sv7FOQqjb23mtxZ2eaL-beTK692k3zwx2qwnPnwe_WnQw-hufx6qgLCDZq1v9Tkc0mf9dxeh2SWffAhd7dIf2BPRnjrvhLRFXKNRZ9jv7oJ6BMbPWYBL0nixfVjM1Q

### currentUser 可以用 idToken/accessToken 访问，获取到的是 accessToken 或 idToken（ 入参是 什么 出参就是 什么 ）
GET http://notuptoyou.com:65101/one/currentUser
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJhenAiOiJkZW1vLWNsaWVudCIsImF1dGhfdGltZSI6MTY4Njg0MDgwMywiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQyNjAzLCJpYXQiOjE2ODY4NDA4MDMsIm5vbmNlIjoiVGlyQnlYaU1xVVl3anRQZjRIbjgzYkQtLXhTbDFqamJDVG1WZHRxSDBUMCIsInNpZCI6ImhvUXpvSVJBT0lnNVYtZV9ZVGdGSDRFOVc1UTNzS1NjM181MzhhYzFtRU0ifQ.iW1IcFSIxFkSZsyGDDPQRNWS0NMgWUavLj8p18ff0XNR87nv1h_K2SqnleTozNb3q41jYr_pHWciXZ0UONY6ggdJhDaKYMVactupzJjwX3nsD57xaxzbnG2B40VzqdukBk8ZNVzB6Oob6_Gk6A8ewfL0jH3KqK4hyIIDbIs8CJQdIL8wDacp_QTwxPFSI5SJLUiUHhEVumN6ggCuxfHGweQ0zhGL4xhfmmMZDNV3Uae7h1EEKvppOkpz6sOkWJY9UIx3JnIYMxfiEFsu6f3ud3jAO1AAuzSsEyU5biff-SrEpesyyPtKTkDqOBSxlh7Cp-KQrbNBDpf0q2TEFUqWcg

### currentSession 可以用 idToken/accessToken 访问，返回值：false
GET http://notuptoyou.com:65101/one/currentSession
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJhenAiOiJkZW1vLWNsaWVudCIsImF1dGhfdGltZSI6MTY4Njg0MDgwMywiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQyNjAzLCJpYXQiOjE2ODY4NDA4MDMsIm5vbmNlIjoiVGlyQnlYaU1xVVl3anRQZjRIbjgzYkQtLXhTbDFqamJDVG1WZHRxSDBUMCIsInNpZCI6ImhvUXpvSVJBT0lnNVYtZV9ZVGdGSDRFOVc1UTNzS1NjM181MzhhYzFtRU0ifQ.iW1IcFSIxFkSZsyGDDPQRNWS0NMgWUavLj8p18ff0XNR87nv1h_K2SqnleTozNb3q41jYr_pHWciXZ0UONY6ggdJhDaKYMVactupzJjwX3nsD57xaxzbnG2B40VzqdukBk8ZNVzB6Oob6_Gk6A8ewfL0jH3KqK4hyIIDbIs8CJQdIL8wDacp_QTwxPFSI5SJLUiUHhEVumN6ggCuxfHGweQ0zhGL4xhfmmMZDNV3Uae7h1EEKvppOkpz6sOkWJY9UIx3JnIYMxfiEFsu6f3ud3jAO1AAuzSsEyU5biff-SrEpesyyPtKTkDqOBSxlh7Cp-KQrbNBDpf0q2TEFUqWcg



### 总结：Server、Client 用 Session 访问，Resource 用 idToken/accessToken 访问（）