### one
GET http://notuptoyou.com:65101/one/aaa
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODY4MzkyMjIsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQ2NDIyLCJpYXQiOjE2ODY4MzkyMjJ9.H-S5mB3nRisAUv13S879oqTA9_7WCvmRqNArVZbozRXXZdlVb8iebAJQgbntgSYz_e34sXO9iq86NzhbRpmOIHmJ-0QhgD61tqZJnuf_s5x2ah6YaIOBJga91Zza4Dt88v5dtRoJpF4fdFTOIC3XTa7-jv5E5hXMMrLXR7eXNBUzp9U7D_7dGPe97hCZuNL7K0KVdSHts9XedtJAfUb_EmAZeIwMK7aFE7luO7o0_llLCT41zK6sfrEJTXoJnEMvOgq2JGD-XZlalp_m-m3ADoLtSxk6hldp5canoiu2xBybSVwOKDukxzt7F1GaRR5jRi5d2a5h5RqWyE-wqSUDSg

### two
GET http://notuptoyou.com:65101/one/bbb
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODY4MzkyMjIsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQ2NDIyLCJpYXQiOjE2ODY4MzkyMjJ9.H-S5mB3nRisAUv13S879oqTA9_7WCvmRqNArVZbozRXXZdlVb8iebAJQgbntgSYz_e34sXO9iq86NzhbRpmOIHmJ-0QhgD61tqZJnuf_s5x2ah6YaIOBJga91Zza4Dt88v5dtRoJpF4fdFTOIC3XTa7-jv5E5hXMMrLXR7eXNBUzp9U7D_7dGPe97hCZuNL7K0KVdSHts9XedtJAfUb_EmAZeIwMK7aFE7luO7o0_llLCT41zK6sfrEJTXoJnEMvOgq2JGD-XZlalp_m-m3ADoLtSxk6hldp5canoiu2xBybSVwOKDukxzt7F1GaRR5jRi5d2a5h5RqWyE-wqSUDSg

### currentUser 获取到的是 accessToken
GET http://notuptoyou.com:65101/one/currentUser
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODY4MzkyMjIsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQ2NDIyLCJpYXQiOjE2ODY4MzkyMjJ9.H-S5mB3nRisAUv13S879oqTA9_7WCvmRqNArVZbozRXXZdlVb8iebAJQgbntgSYz_e34sXO9iq86NzhbRpmOIHmJ-0QhgD61tqZJnuf_s5x2ah6YaIOBJga91Zza4Dt88v5dtRoJpF4fdFTOIC3XTa7-jv5E5hXMMrLXR7eXNBUzp9U7D_7dGPe97hCZuNL7K0KVdSHts9XedtJAfUb_EmAZeIwMK7aFE7luO7o0_llLCT41zK6sfrEJTXoJnEMvOgq2JGD-XZlalp_m-m3ADoLtSxk6hldp5canoiu2xBybSVwOKDukxzt7F1GaRR5jRi5d2a5h5RqWyE-wqSUDSg

### currentSession 无
GET http://notuptoyou.com:65101/one/currentSession
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODY4MzkyMjIsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQ2NDIyLCJpYXQiOjE2ODY4MzkyMjJ9.H-S5mB3nRisAUv13S879oqTA9_7WCvmRqNArVZbozRXXZdlVb8iebAJQgbntgSYz_e34sXO9iq86NzhbRpmOIHmJ-0QhgD61tqZJnuf_s5x2ah6YaIOBJga91Zza4Dt88v5dtRoJpF4fdFTOIC3XTa7-jv5E5hXMMrLXR7eXNBUzp9U7D_7dGPe97hCZuNL7K0KVdSHts9XedtJAfUb_EmAZeIwMK7aFE7luO7o0_llLCT41zK6sfrEJTXoJnEMvOgq2JGD-XZlalp_m-m3ADoLtSxk6hldp5canoiu2xBybSVwOKDukxzt7F1GaRR5jRi5d2a5h5RqWyE-wqSUDSg



### 总结：Server、Client 用 Session 访问，Resource 用 accessToken 访问