### one
GET http://notuptoyou.com:65101/one/aaa
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODY4MzcyMjEsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQ0NDIxLCJpYXQiOjE2ODY4MzcyMjF9.IqsL1hq9mI4kJspxG61d44kJc7BDSUQuPCwlf3FvaiyFT8uFCbf7HNsCb2KleTS3ibo427ZK_NXl3C0HsxQlPVQcU_zq4nQitYVM8yVL20ECdriibKhQGZabehMAZDswkqvOoymjnUwfIMfS8BlrwKrd7JBO1sFU1UAucy4-Jz_E9z1E-ZrdXqCc3jBBiLRnAjTR9ItZuGrqIEqIZKgCy8-v_fl5J7aQpa_vgINK9z8o6Mxbk9HV_5nwTpgXe--OaQ-0l81D8m9erIiudR_tce4BJ9kw_Nzv91n6j77SKzGDPCSYbmT3NO15-TyyEl7JRoVzyRs_Zcs5ZeEB6q814g

### two
GET http://notuptoyou.com:65101/one/bbb
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODY4MzcyMjEsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQ0NDIxLCJpYXQiOjE2ODY4MzcyMjF9.IqsL1hq9mI4kJspxG61d44kJc7BDSUQuPCwlf3FvaiyFT8uFCbf7HNsCb2KleTS3ibo427ZK_NXl3C0HsxQlPVQcU_zq4nQitYVM8yVL20ECdriibKhQGZabehMAZDswkqvOoymjnUwfIMfS8BlrwKrd7JBO1sFU1UAucy4-Jz_E9z1E-ZrdXqCc3jBBiLRnAjTR9ItZuGrqIEqIZKgCy8-v_fl5J7aQpa_vgINK9z8o6Mxbk9HV_5nwTpgXe--OaQ-0l81D8m9erIiudR_tce4BJ9kw_Nzv91n6j77SKzGDPCSYbmT3NO15-TyyEl7JRoVzyRs_Zcs5ZeEB6q814g
