spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
  sql:
    init:
      mode: embedded
      #      username: ${mysql.username}
      #      password: ${mysql.password}
      continue-on-error: false
      schema-locations: classpath*:sql/ddl.sql
#      data-locations: classpath*:sql/data/dml.sql