server:
  port: 65001

spring:
  application:
    name: SERVICE_GOODS
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application-datasource-druid.yml
      - classpath:application-mybatis.yml
      - classpath:application-dubbo.yml
      - classpath:application-log.yml
      - classpath:application-management.yml
  #      - classpath:application-xxljob.yml
  #      - classpath:application-mq-kafka.yml
  #      - classpath:application-mq-rocketmq.yml
  main:
    allow-circular-references: true
