### 获取 token
POST http://notuptoyou.com:65000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZGVtb19jbGllbnQ6MTIzNDU2 # 取值：代码里配置的 clientId:clientSecret 进行 Base64 编码（如当前的：demo_client:123456 => ZGVtb19jbGllbnQ6MTIzNDU2）

# grant_type：授权类型，redirect_uri：代码里配置的 redirectUri ，code：认证后返回的 code
grant_type = authorization_code &
redirect_uri = http://127.0.0.1:65001/redirect &
code = RGPpLfXbiDxN23iCsVTySjJo0nr9_w-q8fJXDJ7pw8AtTcZbGn11o7i-iEC7g99vV6mJ7Ji62HPh_gwpslD-1wzlX0JwPVURqsJLFNeZGc5gAdNDPIQ2CZO7-_ATPfda


### 刷新 token
POST http://notuptoyou.com:65000/oauth2/token
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic ZGVtb19jbGllbnQ6MTIzNDU2

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"
Content-Type: text/plain

refresh_token

--WebAppBoundary
Content-Disposition: form-data; name="refresh_token"
Content-Type: text/plain

# 获取 token 调用返回的 refresh_token
H4dGfaW91bqF3jpuqdhZ3eBs0oXIu4ZlKYXDCFriYDwuxMbC0ZK2Q9QyGzzQH2Br3wcxxeVHWculZPovjUfG1Nee4sC2D6s4i9RAiwB9jp6ThGDfkNAHrv4LLXF8n6SD
