### test 正常访问
GET http://notuptoyou.com:65000/test
Content-Type: application/json
Cookie: JSESSIONID=DED30FFC74B97C208100B5C9CE571A58

### currentUser 没 idToken 、accessToken ，获取到的信息里包含 sessionId
GET http://notuptoyou.com:65000/currentUser
Content-Type: application/json
Cookie: JSESSIONID=DED30FFC74B97C208100B5C9CE571A58

### currentSession 有（ 域：notuptoyou.com ）
GET http://notuptoyou.com:65000/currentSession
Content-Type: application/json
Cookie: JSESSIONID=DED30FFC74B97C208100B5C9CE571A58


### 总结：Server、Client 用 Session 访问，Resource 用 accessToken 访问