### redirect
GET http://notuptoyou.com:65001/redirect
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxMjM0NTYiLCJhdWQiOiJmaXJzdF9jbGllbnQiLCJuYmYiOjE2ODU1Mzc4NzAsInNjb3BlIjpbInNlcnZpY2UucmVhZCJdLCJpc3MiOiJodHRwOi8vbm90dXB0b3lvdS5jb206NjUwMDAiLCJleHAiOjE2ODU1NDUwNzAsImlhdCI6MTY4NTUzNzg3MH0.kv9G1UUcPDueHnVoupC9gcJrpqGuLafbU-F_Ba0NiDwqOr4uf3O62wetIgDyzl5inXs6tvzwK27D7qOfNWTq3Ffy7ZQTqzJvQHdG_DI2Fy7l5LBRlu0B89eue3u0AVxALOlGyLpOT4Ok1iJdeJMme5aVR4vLA6_WvUANfP4KRLgs3b5HOjauvtLXOrFQxcvBlsJPerEIfLTYVpGXtqriCAsrn9DixU8TlzsDp1OUg33gcvABPLmhy0UNDrXLvZgztDT8lWNgd6bqxOL_vf_GRXSaoYx-_FwaExoCGHJWQImtjnfMvkbQKfS67rFo9ht0kIgyzZIOc1eFJhGo-Lsl3Q
