server:
  port: 65002
spring:
  application:
    name: oauth_mode_code_client
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application-mybatis.yml
      - classpath:application-redis.yml
      - classpath:application-s-jwt.yml
      - classpath:application-s-oauth.yml
      - classpath:application-log.yml