mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描，多个 package 用逗号或者分号分隔
  typeAliasesPackage: com.code
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      # 驼峰下划线转换
      table-underline: true
      # 是否开启大写命名，默认不开启
      # capital-mode: true
      # 逻辑删除配置
      # logic-delete-value: 1
      # logic-not-delete-value: 0
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
