spring:
  oauth:
    custom:
      server:
        issuer: http://notuptoyou.com:65001
        default-registration-client:
          client-id: demo-client
          client-secret: 123456
          client-name: Demo客户端
          scopes: openid,read,write
          redirect-uris: http://127.0.0.1:65002/login/oauth2/code/first-registration,http://127.0.0.1:65002/authorized