spring:
  security:
    custom:
      default-user:
        name: snow
        password: 666666
        roles: USER
      login:
        basic-url: http://127.0.0.1:65001
        provider-url: /login
        success-url: /oauth2/authorization/first-registration