### 获取 token
POST http://notuptoyou.com:65000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic dXNlcl9jZW50ZXI6dXNlcl9jZW50ZXJfMTIzNDU2 # 取值：代码里配置的 clientId:clientSecret 进行 Base64 编码（如当前的：user_center:user_center_123456 => dXNlcl9jZW50ZXI6dXNlcl9jZW50ZXJfMTIzNDU2）

# grant_type：授权类型，redirect_uri：代码里配置的 redirectUri ，code：认证后返回的 code
grant_type = authorization_code &
redirect_uri = https://www.bing.com &
code = LxsMoBCOVhapry6lFTOiO95de07xt6egZ37ut6nyWvL7A6ZGHqpp4D-V439ifnUAbCUF3CBEV68QFBuYT9KzBzK4CiEHEuL4-sa5einmj2ebczAbadiGlHXRIFlKBFSr


### 刷新 token
POST http://notuptoyou.com:65000/oauth2/token
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic Zmlyc3RfY2xpZW50OjEyMzQ1Ng==

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"
Content-Type: text/plain

refresh_token

--WebAppBoundary
Content-Disposition: form-data; name="refresh_token"
Content-Type: text/plain

# 获取 token 调用返回的 refresh_token
xE8BkjDgja4Ta0tdGQ1nEZEWuFUx8ykf0hNcjdCUK4u-yhbsRlZ2PnbvHJJxs3P5QQjvYi-KkysUXwuvu6DFL91uNeuNBvewUZ7k9mAYA9qfpg3dqx8qgUfYaQj1V6DG
