### test
POST http://127.0.0.1:65301/gateway
Content-Type: application/json; charset=UTF-8

{
  "api": "template.test"
}

### 保存
POST http://127.0.0.1:65301/gateway
Content-Type: application/json; charset=UTF-8

{
  "api": "template.save",
  "content": "{\"name\":\"测试3\",\"age\":16}"
}

### page
POST http://127.0.0.1:65301/gateway
Content-Type: application/json; charset=UTF-8

{
  "api": "template.page",
  "content": "{\"name\":\"测试\"}"
}
