### currentUser
GET http://127.0.0.1:65001/currentUser
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJuYmYiOjE2ODY4MzcyMjEsInNjb3BlIjpbInJlYWQiLCJvcGVuaWQiXSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg2ODQ0NDIxLCJpYXQiOjE2ODY4MzcyMjF9.IqsL1hq9mI4kJspxG61d44kJc7BDSUQuPCwlf3FvaiyFT8uFCbf7HNsCb2KleTS3ibo427ZK_NXl3C0HsxQlPVQcU_zq4nQitYVM8yVL20ECdriibKhQGZabehMAZDswkqvOoymjnUwfIMfS8BlrwKrd7JBO1sFU1UAucy4-Jz_E9z1E-ZrdXqCc3jBBiLRnAjTR9ItZuGrqIEqIZKgCy8-v_fl5J7aQpa_vgINK9z8o6Mxbk9HV_5nwTpgXe--OaQ-0l81D8m9erIiudR_tce4BJ9kw_Nzv91n6j77SKzGDPCSYbmT3NO15-TyyEl7JRoVzyRs_Zcs5ZeEB6q814g
Cookie: JSESSIONID=B12D423366A56A3813EEDD982A100DFA

### currentSession
GET http://127.0.0.1:65001/currentSession
Content-Type: application/json
Authorization: Bearer eyJ4NXQjUzI1NiI6IjNzbVd1M0FsbGpobEZhTWQyMDJJN3A1Rm83alhJM2dCdldTOWNSaUlmMlkiLCJraWQiOiJkZW1vS2V5IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzbm93IiwiYXVkIjoiZGVtby1jbGllbnQiLCJhenAiOiJkZW1vLWNsaWVudCIsImF1dGhfdGltZSI6MTY4NTg3MjYyNSwiaXNzIjoiaHR0cDovL25vdHVwdG95b3UuY29tOjY1MDAwIiwiZXhwIjoxNjg1ODc0NDI2LCJpYXQiOjE2ODU4NzI2MjYsIm5vbmNlIjoiRWdoTU01OENZNHpyUmVrNS05b2xRZkx0VnhhYjZCN2FxYU0tV1k1Z20yYyIsInNpZCI6InQ4VkpPX2xkYzZLSF9SUHQtMS1FMlhWeURvaXk1TmJWa05Ib0JNM29oVW8ifQ.L6qgnwAUDZk_f3b_sA1He5RlwXLZdCvAPhkUS-cLy1HVWLutKXI6jdZuih7cBeDJvZDco-dJa1XkQmscY-PF7xpIA2eZfWMKbvsXqeGSgL9Bew14Sf9OXrohQWwLc-vhtADDCoXv8jQN3GJPu50PVlxS45ZwwW70FLdv2LeSkaTTegyEAYDJiIsDPvL1sh0mBEfWjVhcpiNO-P5WXYYu5hTT89mNHRHsvHnjUrJDsamxIngaqYXtGyLnTB0k48SpkJwZAMonRzyVGrQ8wooLC8trSr2NL8n7cPRQwgTxZi0BZA69YfQhUsBddq1_cuobkRwrIEzV3O0SppCa76-kMg
Cookie: JSESSIONID=B12D423366A56A3813EEDD982A100DFA