### currentUser 获取到的是 idToken
GET http://127.0.0.1:65001/currentUser
Content-Type: application/json
Cookie: JSESSIONID=F44653AD87C1F635D9D73912443A99D8

### currentSession 有（ 域：127.0.0.1 ）
GET http://127.0.0.1:65001/currentSession
Content-Type: application/json
Cookie: JSESSIONID=F44653AD87C1F635D9D73912443A99D8



### 总结：Server、Client 用 Session 访问，Resource 用 accessToken 访问