spring:
  security:
    oauth2:
      client:

        registration:
          # 客户端：与 Server 的设置保持一致
          demoClient:
            client-id: demo_client
            client-secret: 123456
            client-name: demo_client_name
            scope: read,write
            authorization-grant-type: authorization_code
            provider: demoAuthorization
            redirect-uri: '{baseUrl}/{action}/oauth2/code/demoClient'
            # 认证方法
            client-authentication-method: client_secret_basic

        provider:
          # 服务提供地址
          demoAuthorization:
            # 请求授权码地址
            authorization-uri: http://notuptoyou.com:65000/oauth2/authorize
            # 请求令牌地址
            token-uri: http://notuptoyou.com:65000/oauth2/token
            # 获取用户信息的地址：必须和 infra-authorization 服务中自己定义的 Controller 的 RequestMapping 路径一致
            user-info-uri: http://notuptoyou.com:65000/oauth2/user
            # 获取到的用户信息中用户名的属性名
            user-name-attribute: name
            user-info-authentication-method: GET